Revert "Make libutils test compile on the host"
Fails mac build: "system/core/include/utils/Looper.h:25:10: fatal error: 'sys/epoll.h' file not found"

This reverts commit 910c04663cbd6f8facf2ac6a3f6ee30d2be5a241.

Change-Id: Ib558b8f5a303b55ab32a399d338d8aac0fae32b2