Revert "adb: add transport benchmark."
This reverts commit 48517544f7b7ca2caae68f6eac3980a5324374e4.

Reason for revert: Breaks aosp-master renderscript and sdk_mac:
  error: system/core/adb/Android.bp:199:19: unrecognized property "host_supported"

Change-Id: Ifd75921dcdf5dce57f98833a913540914984b293